FROM golang:1.24

WORKDIR /stay_watch-slackbot

RUN apt-get update &&\
    apt-get install -y git &&\
    apt-get install -y lsof &&\
    mkdir src

COPY ./src /stay_watch-slackbot/src

RUN cd src &&\
    go build -o slackbot

CMD ["./slackbot"]