FROM golang:1.24

WORKDIR /stay_watch-slackbot

RUN apt update &&\
    apt install -y git &&\
    apt install -y lsof &&\
    mkdir src

COPY ./src /stay_watch-slackbot/src

RUN cd src &&\
    go build -o slackbot

CMD ["./slackbot"]