// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/activities/probabilities": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activities"
                ],
                "summary": "全活動の時間帯別発生確率を取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "曜日 (MySQL WEEKDAY形式: 0=月, 6=日)。省略時は今日の曜日",
                        "name": "weekday",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/board": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "board"
                ],
                "summary": "共有モニター用の表示データを取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.BoardData"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/events": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Event一覧を取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "取得するEventのID",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "絞り込む分類（digital または analog）",
                        "name": "game_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/events/{id}/probability": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "イベントの発生確率を取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "イベントID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "曜日 (MySQL WEEKDAY形式: 0=月, 6=日)",
                        "name": "weekday",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "時刻 (HH:MM形式, JST。デフォルト: 現在時刻)",
                        "name": "time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/logs": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "ログを一括登録",
                "parameters": [
                    {
                        "description": "登録するログエントリのリスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.RegisterLogsRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/statuses": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statuses"
                ],
                "summary": "Status一覧を取得",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "statuses"
                ],
                "summary": "Statusを一括登録",
                "parameters": [
                    {
                        "description": "登録するStatus名のリスト",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controller.RegisterStatusesRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.LogEntry": {
            "type": "object",
            "required": [
                "event_id",
                "event_time",
                "status_id"
            ],
            "properties": {
                "event_id": {
                    "description": "対象のEventのID（文字列で指定）",
                    "type": "string",
                    "example": "1"
                },
                "event_time": {
                    "description": "イベント発生日時。RFC3339形式のJST",
                    "type": "string",
                    "example": "2006-01-02T15:04:05+09:00"
                },
                "participate_users": {
                    "description": "参加メンバのstay_watch_idリスト（空可）",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        1,
                        2
                    ]
                },
                "room_users": {
                    "description": "在室メンバのstay_watch_idリスト（空可）",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "example": [
                        3,
                        4
                    ]
                },
                "status_id": {
                    "description": "対象のStatusのID",
                    "type": "integer",
                    "example": 2
                }
            }
        },
        "controller.RegisterLogsRequest": {
            "type": "object",
            "required": [
                "logs"
            ],
            "properties": {
                "logs": {
                    "description": "登録するログエントリの配列（1件以上）",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/controller.LogEntry"
                    }
                }
            }
        },
        "controller.RegisterStatusesRequest": {
            "type": "object",
            "required": [
                "names"
            ],
            "properties": {
                "names": {
                    "description": "登録するStatus名の配列（1件以上、重複不可）",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "作業中",
                        "休憩中"
                    ]
                }
            }
        },
        "service.BoardActivity": {
            "type": "object",
            "properties": {
                "headcount": {
                    "description": "想定人数",
                    "type": "integer",
                    "example": 4
                },
                "likelihood": {
                    "description": "発生確率の高さ",
                    "type": "string",
                    "enum": [
                        "high",
                        "mid",
                        "low"
                    ],
                    "example": "high"
                },
                "name": {
                    "description": "活動（イベント）名",
                    "type": "string",
                    "example": "人狼"
                }
            }
        },
        "service.BoardData": {
            "type": "object",
            "properties": {
                "currentTime": {
                    "description": "データ生成時点の現在時刻（JST）",
                    "type": "string",
                    "example": "2006-01-02T15:04:05+09:00"
                },
                "presence": {
                    "description": "在室情報",
                    "allOf": [
                        {
                            "$ref": "#/definitions/service.BoardPresence"
                        }
                    ]
                },
                "timeBlocks": {
                    "description": "時間帯（昼/夕方/夜）ごとの表示データ",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.BoardTimeBlock"
                    }
                }
            }
        },
        "service.BoardPerson": {
            "type": "object",
            "properties": {
                "arrival": {
                    "description": "来訪見込み度",
                    "type": "string",
                    "enum": [
                        "likely",
                        "maybe"
                    ],
                    "example": "likely"
                },
                "avatarUrl": {
                    "description": "アイコン画像URL",
                    "type": "string",
                    "example": "https://example.com/avatar.png"
                },
                "name": {
                    "description": "ユーザー名",
                    "type": "string",
                    "example": "山田太郎"
                }
            }
        },
        "service.BoardPresence": {
            "type": "object",
            "properties": {
                "members": {
                    "description": "在室中メンバーの配列（常に空配列）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.BoardPresentMember"
                    }
                }
            }
        },
        "service.BoardPresentMember": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "description": "アイコン画像URL",
                    "type": "string",
                    "example": "https://example.com/avatar.png"
                },
                "name": {
                    "description": "ユーザー名",
                    "type": "string",
                    "example": "山田太郎"
                }
            }
        },
        "service.BoardTimeBlock": {
            "type": "object",
            "properties": {
                "activities": {
                    "description": "この時間帯に発生しうる活動一覧",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.BoardActivity"
                    }
                },
                "id": {
                    "description": "時間帯の識別子",
                    "type": "string",
                    "enum": [
                        "noon",
                        "evening",
                        "night"
                    ],
                    "example": "noon"
                },
                "isNow": {
                    "description": "現在時刻がこの時間帯に含まれるか",
                    "type": "boolean",
                    "example": true
                },
                "label": {
                    "description": "時間帯の表示名",
                    "type": "string",
                    "example": "昼"
                },
                "people": {
                    "description": "この時間帯に来訪見込みのある人一覧",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.BoardPerson"
                    }
                },
                "range": {
                    "description": "時間帯の範囲（表示用文字列）",
                    "type": "string",
                    "example": "12:00-17:00"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Stay Watch Slackbot API",
	Description:      "研究室の来訪予測・活動管理のためのAPI",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
