services:
  api:
    container_name: ${API_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./docker/app/dockerfile
      target: production  # 本番環境用ステージを指定
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      # ソースコードのマウントは不要（バイナリが埋め込まれている）
      - ./log:/stay_watch-slackbot/log
    environment:
      - GIN_MODE=${GIN_MODE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PROTOCOL=${MYSQL_PROTOCOL}
      - MYSQL_DBNAME=${MYSQL_DBNAME}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      - SLACK_BOT_USER_OAUTH_TOKEN=${SLACK_BOT_USER_OAUTH_TOKEN}
      - STAYWATCH_URL=${STAYWATCH_URL}
      - STAYWATCH_USERS_PATH=${STAYWATCH_USERS_PATH}
      - STAYWATCH_PROBABILITY_PATH=${STAYWATCH_PROBABILITY_PATH}
      - STAYWATCH_TIME_PATH=${STAYWATCH_TIME_PATH}
      - STAYWATCH_API_KEY=${STAYWATCH_API_KEY}
    ports:
      - ${API_PORT}:8085
    depends_on:
        db:
          condition: service_healthy

  db:
    container_name: ${MYSQL_CONTAINER_NAME}
    image: mysql:8.4
    restart: unless-stopped
    volumes:
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysql_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 5

volumes:
  mysql_data:
    driver: local
